; Generated by abccc - do not edit by hand.
; Stream format version 1.
        .export _landerbass_music
        .segment "RODATA"
_landerbass_music:
        .byte $93
        .byte $01
        .byte $80
        .byte $00
        .byte $84
        .byte $00
        .byte $00
        .byte $01
        .byte $00
        .byte $46
        .byte $88
        .byte $01
        .byte <Lenv0, >Lenv0
        .byte $89
        .byte $01
        .byte $94
        .byte $80
        .byte $15
        .byte $15
        .byte $11
        .byte $11
        .byte $18
        .byte $18
        .byte $10
        .byte $10
        .byte $81
        .byte $00
Lenv0:
        .byte $00
        .byte $03
        .byte $18
        .byte $03
        .byte $14
        .byte $00
        .byte $12
        .byte $FC
