/*
** SPDX-License-Identifier: MPL-2.0
**
** This Source Code Form is subject to the terms of the Mozilla Public License,
** v. 2.0. If a copy of the MPL was not distributed with this file, You can
** obtain one at https://mozilla.org/MPL/2.0/.
**
** Part of the Lynx Game Development SDK (lynxcc). See doc/licenses.html.
*/

/*
** multicart.c -- "lnx multicart": write a lynxdir .mak for a multicart.
** See multicart.h and design/LYNX_MULTICART_DESIGN.md.
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "multicart.h"

/* Parse an unsigned decimal argument. Returns 0 on success. */
static int ParseUInt(const char* s, unsigned* out)
{
    char*         end;
    unsigned long v;

    if (!s || !*s) {
        return -1;
    }
    v = strtoul(s, &end, 0);
    if (*end != '\0') {
        return -1;
    }
    *out = (unsigned)v;
    return 0;
}

int MulticartMak(int argc, char** argv, int start)
{
    const char* menu     = NULL;
    const char* output   = NULL;
    unsigned    blocksz  = MULTICART_BLOCKSIZE;
    unsigned    dirstart = MULTICART_DIRSTART;
    unsigned    diroff   = MULTICART_DIROFFSET;
    const char* games[256];
    int         ngames   = 0;
    int         i;
    FILE*       f;

    for (i = start; i < argc; i++) {
        const char* a = argv[i];
        if (strcmp(a, "--menu") == 0) {
            if (++i >= argc) { fprintf(stderr, "lnx: --menu needs a file\n"); return 1; }
            menu = argv[i];
        } else if (strcmp(a, "--blocksize") == 0) {
            if (++i >= argc || ParseUInt(argv[i], &blocksz) != 0) {
                fprintf(stderr, "lnx: bad --blocksize\n"); return 1;
            }
            if (blocksz != 512 && blocksz != 1024 && blocksz != 2048) {
                fprintf(stderr, "lnx: --blocksize must be 512, 1024 or 2048\n");
                return 1;
            }
        } else if (strcmp(a, "--dirstart") == 0) {
            if (++i >= argc || ParseUInt(argv[i], &dirstart) != 0) {
                fprintf(stderr, "lnx: bad --dirstart\n"); return 1;
            }
        } else if (strcmp(a, "--diroffset") == 0) {
            if (++i >= argc || ParseUInt(argv[i], &diroff) != 0) {
                fprintf(stderr, "lnx: bad --diroffset\n"); return 1;
            }
        } else if (strcmp(a, "-o") == 0 || strcmp(a, "--output") == 0) {
            if (++i >= argc) { fprintf(stderr, "lnx: -o needs a file\n"); return 1; }
            output = argv[i];
        } else if (a[0] == '-' && a[1] != '\0') {
            fprintf(stderr, "lnx: unknown multicart option '%s'\n", a);
            return 1;
        } else {
            if (ngames >= (int)(sizeof(games) / sizeof(games[0]))) {
                fprintf(stderr, "lnx: too many game files\n");
                return 1;
            }
            games[ngames++] = a;
        }
    }

    if (!menu) {
        fprintf(stderr, "lnx: 'multicart' requires --menu <file>\n");
        return 1;
    }
    if (ngames == 0) {
        fprintf(stderr, "lnx: 'multicart' requires at least one game file\n");
        return 1;
    }

    if (output) {
        f = fopen(output, "w");
        if (!f) {
            fprintf(stderr, "lnx: cannot write '%s'\n", output);
            return 1;
        }
    } else {
        f = stdout;
    }

    /* The mini-loader (NEWMINI_FB68) runs the first (EPYX) entry -- the menu.
    ** The menu's own runtime loader then indexes the BLL game directory at
    ** #DIROFFSET. Keep the ROM-wide commands first; order of the BLL files sets
    ** the game numbers multicart_run() takes (0-based). */
    fprintf(f, "; Generated by lnx multicart -- lynxdir multicart layout.\n");
    fprintf(f, "; Build the cart with:  lynxdir %s\n",
            output ? output : "<this>.mak");
    fprintf(f, "#NEWMINI_FB68\n");
    fprintf(f, "#BLOCKSIZE %u\n", blocksz);
    fprintf(f, "#DIRSTART %u\n", dirstart);
    fprintf(f, "#EPYX\n");
    fprintf(f, "%s\n", menu);
    fprintf(f, "#DIROFFSET %u\n", diroff);
    fprintf(f, "#BLL\n");
    for (i = 0; i < ngames; i++) {
        fprintf(f, "%s\n", games[i]);
    }

    if (f != stdout) {
        fclose(f);
    }
    return 0;
}
