; Generated by abccc - do not edit by hand.
; Stream format version 1.
        .export _theme_music
        .segment "RODATA"
_theme_music:
        .byte $93
        .byte $01
        .byte $80
        .byte $00
        .byte $84
        .byte $00
        .byte $00
        .byte $01
        .byte $00
        .byte $64
        .byte $88
        .byte $01
        .byte <Lenv0, >Lenv0
        .byte $89
        .byte $01
        .byte $94
        .byte $24
        .byte $24
        .byte $26
        .byte $28
        .byte $29
        .byte $2B
        .byte $2D
        .byte $2F
        .byte $30
        .byte $81
        .byte $82
        .byte $90
        .byte $00
Lenv0:
        .byte $00
        .byte $03
        .byte $0D
        .byte $08
        .byte $0C
        .byte $00
        .byte $19
        .byte $FC
