/*
** SPDX-License-Identifier: MIT
**
** Lynx Game Development SDK example/template, (c) 2026 the lynxcc authors.
** Provided under the MIT License; copy it into your own projects freely.
** See the LICENSE file in this directory.
*/

/*
** Sprite sheets the easy way: sp65's --sprite-sheet driver.
**
** One source image, sheet.pcx, holds a 4-frame bouncing-ball animation as a
** horizontal strip of four 16x16 cells (64x16 total, generated by
** sheet.pcx.py). Instead of carrying four image files and running sp65 four
** times, the Makefile slices the whole strip in a single call:
**
**   sp65 -r sheet.pcx \
**        --sprite-sheet name=sheet_anim.h,ident=sheet_anim,fw=16,fh=16,mode=packed
**
** That emits ONE header, sheet_anim.h, containing:
**   - sheet_anim_data[]  : every frame encoded back-to-back, byte-for-byte the
**                          same as encoding each cell on its own;
**   - sheet_anim[]       : a const table of pointers, sheet_anim[i] -> frame i;
**   - sheet_anim_COUNT / _WIDTH / _HEIGHT / _COLORS.
**
** Animating is then just "scb.data = (unsigned char*)sheet_anim[frame]". The
** companion sample spriteslice.c draws the SAME four frames built the manual
** way (four --slice/--pop headers) to prove the driver only repackages the
** data - see design/LYNX_SPRITE_SHEET_DESIGN.md.
**
** Build:  cl65 -Ors -o spritesheet.lnx spritesheet.c  (after generating header)
*/

#include <lynx/lynx.h>
#include <lynx/gfx.h>
#include <6502.h>

#include "sheet_anim.h"

/* 4-colour palette matching sheet.pcx: pen 0 = transparent background,
** 1 = ball body, 2 = highlight, 3 = rim shadow. Lynx format: 16 green nibbles,
** then 16 (blue<<4 | red) bytes.
*/
static const unsigned char palette[32] = {
    /* green nibble per pen 0..15 */
    0x0, 0xC, 0xF, 0x3, 0x0, 0x0, 0x0, 0x0,
    0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
    /* blue<<4 | red per pen 0..15 */
    0x00, 0xF3, 0xFC, 0x70, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};

/* Identity penpal, 2 bpp (4 colours). data/hpos/vpos are filled in per draw. */
static SCB_REHV_PAL scb = {
    BPP_2 | TYPE_NORMAL, PACKED | REHV, NO_COLLIDE,
    0, 0, 0, 0, 0x0400, 0x0400,                 /* 4x scale: 16px art -> 64px */
    { 0x01, 0x23, 0x45, 0x67, 0x89, 0xAB, 0xCD, 0xEF }
};

void main (void)
{
    unsigned char frame = 0;
    unsigned char tick  = 0;

    gfx_init ();
    CLI ();
    gfx_setframerate (60);
    gfx_setpalette (palette);

    for (;;) {
        while (gfx_busy ()) {}

        gfx_setcolor (0);
        gfx_clear ();

        gfx_setcolor (2);
        gfx_outtextxy (24, 8, "SPRITE SHEET");
        gfx_outtextxy (8, 20, "sp65 --sprite-sheet");

        /* Draw the current frame straight out of the generated table. */
        scb.data = (unsigned char *)sheet_anim[frame];
        scb.hpos = 48;
        scb.vpos = 40;
        gfx_sprite (&scb);

        gfx_updatedisplay ();

        /* Advance the animation a few vsyncs per frame. */
        if (++tick >= 8) {
            tick = 0;
            frame = (unsigned char)((frame + 1) % sheet_anim_COUNT);
        }
    }
}
