/*
** SPDX-License-Identifier: MIT
**
** Lynx Game Development SDK example/template, (c) 2026 the lynxcc authors.
** Provided under the MIT License; copy it into your own projects freely.
** See the LICENSE file in this directory.
*/

/*
** Build-time packed sprite assets for cc65 (Atari Lynx).
**
** Where packtest.c proves the PACKED and LITERAL encodings are equivalent by
** packing a sprite at *runtime*, this sample proves the same thing for assets
** packed *offline at build time* by sp65 - the sprite converter that ships in
** this tree (src/sp65/lynxsprite.c, the "lynx-sprite" target).
**
** The 16x16 source image lives in heart.pcx. The Makefile runs sp65 twice on
** it before this file is compiled:
**
**   sp65 -r heart.pcx -c lynx-sprite,mode=packed  -w heart_packed.h,ident=heart_packed
**   sp65 -r heart.pcx -c lynx-sprite,mode=literal -w heart_literal.h,ident=heart_literal
**
** Each call emits a C header with a "const unsigned char <ident>[]" sprite
** data block plus <ident>_WIDTH / _HEIGHT / _COLORS defines. We #include both
** and draw them with an identical SCB - same penpal, same 1x scale, only the
** PACKED bit of SPRCTL1 and the data pointer differ. The packed block is the
** smaller of the two (heart_packed.h vs heart_literal.h); both must render
** pixel-for-pixel identically.
**
** heart.pcx uses pen 0 along its entire left and right edges, so no scan line
** ends on an odd pen value: this side-steps Suzy's last-pixel bug without a
** pad byte (see design/LYNX_SPRITE_PADBYTE_DESIGN.md sec. 5 and the sp65
** "literal" notes in doc/sp65.html). heart.pcx was generated by heart.pcx.py.
**
** Build:  cl65 -Ors -o spritetest.lnx spritetest.c (after generating headers)
*/

#include <lynx/lynx.h>
#include <lynx/gfx.h>
#include <6502.h>

#include "heart_packed.h"
#include "heart_literal.h"

/* 16-entry palette: pen 0 = black background (transparent via penpal value 0),
** pen 1 = heart red, pen 2 = highlight pink. Lynx format: 16 green nibbles,
** then 16 (blue<<4 | red) bytes.
*/
static const unsigned char palette[32] = {
    /* green nibble per pen 0..15 */
    0x0, 0x3, 0xC, 0x1, 0x0, 0x0, 0x0, 0x0,
    0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xF,
    /* blue<<4 | red per pen 0..15 */
    0x00, 0xF2, 0xFD, 0x17, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF
};

/* Identity penpal: pixel value v draws pen v (value 0 -> pen 0, transparent).
** heart.pcx is 3-colour -> 2 bpp, so Suzy reads only the first 4 nibbles
** (penpal bytes 0..1); the rest are ignored. data/PACKED are set per draw.
*/
static SCB_REHV_PAL scb = {
    BPP_2 | TYPE_NORMAL, LITERAL | REHV, NO_COLLIDE,
    0, 0, 0, 0, 0x0100, 0x0100,                 /* 1x scale: 1 src px = 1 px */
    { 0x01, 0x23, 0x45, 0x67, 0x89, 0xAB, 0xCD, 0xEF }
};

static void show (const unsigned char *data, unsigned char ctl1,
                  signed int x, signed int y)
{
    scb.data    = (unsigned char *)data;
    scb.sprctl1 = (unsigned char)(ctl1 | REHV);
    scb.hpos    = x;
    scb.vpos    = y;
    gfx_sprite (&scb);
}

static void draw (void)
{
    gfx_setcolor (0);
    gfx_clear ();

    gfx_setcolor (15);
    gfx_outtextxy (28, 14, "LITERAL");        /* over the left heart  */
    gfx_outtextxy (104, 14, "PACKED");        /* over the right heart */

    /* Same source image, two offline encodings, drawn at 3x via the SCB so the
    ** 16x16 art is easy to eyeball. heart_*_HEIGHT confirm both are 16 tall.
    */
    scb.hsize = scb.vsize = 0x0300;             /* 3x scale */
    show (heart_literal, LITERAL, 32, 28);
    show (heart_packed,  PACKED,  104, 28);

    gfx_setcolor (15);
    gfx_outtextxy (12, 84, "PACKED == LITERAL");
}

void main (void)
{
    gfx_init ();
    CLI ();
    gfx_setframerate (60);
    gfx_setpalette (palette);

    for (;;) {
        while (gfx_busy ()) {}
        draw ();
        gfx_updatedisplay ();
    }
}
